[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_GA_ID = "G-1RS27QF82W"
  NEXT_PUBLIC_SUPABASE_URL = "https://nnlekbywldrainqhvgif.supabase.co"
  NEXT_PUBLIC_SITE_URL = "https://yannova.be"

[[plugins]]
  package = "@netlify/plugin-nextjs"
