-- Seed projects from projects.json
INSERT INTO "Project" ("id", "title", "description", "category", "imageUrl", "featured", "published", "views", "createdAt", "updatedAt")
VALUES 
    (gen_random_uuid()::text, 'Vloerverwarming Installatie', 'Realisatie van een project: Vloerverwarming Installatie. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/underfloor_heating_installation.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Structurele Stalen Balk Installatie', 'Realisatie van een project: Structurele Stalen Balk Installatie. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/structural_steel_beam_install.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Trap Installatie', 'Realisatie van een project: Trap Installatie. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/staircase_installation.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Dakrenovatie', 'Realisatie van een project: Dakrenovatie. Hoogwaardige afwerking door Yannova Bouw.', 'Dakrenovatie', '/images/projects/roof_renovation_scaffolding.png', true, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Raamvervanging', 'Realisatie van een project: Raamvervanging. Hoogwaardige afwerking door Yannova Bouw.', 'Ramen & Deuren', '/images/projects/replacing_windows_no_people.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Renovatie Werken', 'Realisatie van een project: Renovatie Werken. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/renovation_works_example.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Loodgieterswerk', 'Realisatie van een project: Loodgieterswerk. Hoogwaardige afwerking door Yannova Bouw.', 'Sanitair', '/images/projects/plumbing_rough_in.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Moderne Uitbouw', 'Realisatie van een project: Moderne Uitbouw. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/modern_extension_construction.png', true, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Keukenrenovatie', 'Realisatie van een project: Keukenrenovatie. Hoogwaardige afwerking door Yannova Bouw.', 'Keuken', '/images/projects/kitchen_renovation_stripout.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Interieur Renovatie', 'Realisatie van een project: Interieur Renovatie. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/interior_renovation_sliding_doors.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Visgraat Vloer', 'Realisatie van een project: Visgraat Vloer. Hoogwaardige afwerking door Yannova Bouw.', 'Vloeren', '/images/projects/herringbone_flooring_install.png', true, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Stucwerk', 'Realisatie van een project: Stucwerk. Hoogwaardige afwerking door Yannova Bouw.', 'Afwerking', '/images/projects/fresh_plastering_skim.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Elektrische Installatie', 'Realisatie van een project: Elektrische Installatie. Hoogwaardige afwerking door Yannova Bouw.', 'Elektriciteit', '/images/projects/electrical_wiring_fix.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Badkamer Renovatie', 'Realisatie van een project: Badkamer Renovatie. Hoogwaardige afwerking door Yannova Bouw.', 'Sanitair', '/images/projects/bathroom_renovation_tiling.png', true, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'Zolder Conversie', 'Realisatie van een project: Zolder Conversie. Hoogwaardige afwerking door Yannova Bouw.', 'Totaalrenovatie', '/images/projects/attic_conversion_insulation.png', false, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
